name: ccwav-sync

on:
  schedule:
    - cron: '52 * * * *'

  workflow_dispatch:
  
jobs:
  repo-sync:
    if: ${{ github.repository != 'ccwav/QLScript2' }}

    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/ccwav/QLScript2"
          source_branch: "main"
          destination_branch: "ccwav"
          sync_tags: "true"
          github_token: ${{ secrets.PAT }}
