name: faker2-backup-sync
on:
  schedule:
    - cron: '46 * * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-faker2-backup-GithubSync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync faker2-backup-GithubSync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/carpsz/faker2.git"
          source_branch: "main"
          destination_branch: "faker2-backup"
          github_token: ${{ secrets.PAT }}
