name: faker3-sync
on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-faker3-GithubSync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync faker3-GithubSync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/shufflewzc/faker3.git"
          source_branch: "main"
          destination_branch: "faker3"
          github_token: ${{ secrets.PAT }}
