name: gys619-sync

on:
  schedule:
    - cron: '29 * * * *'

  workflow_dispatch:
  
jobs:
  repo-sync:
    if: ${{ github.repository != 'gys619/Absinthe.git' }}

    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/gys619/Absinthe.git"
          source_branch: "main"
          destination_branch: "gys619"
          sync_tags: "true"
          github_token: ${{ secrets.PAT }}
