name: gys619-sync
on:
  schedule:
    - cron: '29 * * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-gys619-GithubSync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync gys619-GithubSync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/gys619/Absinthe.git"
          source_branch: "main"
          destination_branch: "gys619"
          github_token: ${{ secrets.PAT }}
