name: JDHelloWorld-sync
on:
  schedule:
    - cron: '21 * * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-JDHelloWorld-GithubSync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync JDHelloWorld-GithubSync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/JDHelloWorld/jd_scripts.git"
          source_branch: "main"
          destination_branch: "JDHelloWorld"
          github_token: ${{ secrets.PAT }}
