name: JDHelloWorld-sync

on:
  schedule:
    - cron: '21 * * * *'

  workflow_dispatch:
  
jobs:
  repo-sync:
    if: ${{ github.repository != 'JDHelloWorld/jd_scripts.git' }}

    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/JDHelloWorld/jd_scripts.git"
          source_branch: "main"
          destination_branch: "JDHelloWorld"
          sync_tags: "true"
          github_token: ${{ secrets.PAT }}
