name: KingRan-sync

on:
  schedule:
    - cron: '35 * * * *'

  workflow_dispatch:
  
jobs:
  repo-sync:
    if: ${{ github.repository != 'KingRan/KR.git' }}

    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/KingRan/KR.git"
          source_branch: "main"
          destination_branch: "KingRan"
          sync_tags: "true"
          github_token: ${{ secrets.PAT }}
