name: okyyds-sync

on:
  schedule:
    - cron: '12 * * * *'

  workflow_dispatch:
  
jobs:
  repo-sync:
    if: ${{ github.repository != 'okyyds/yydspure.git' }}

    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/okyyds/yydspure.git"
          source_branch: "master"
          destination_branch: "okyyds"
          sync_tags: "true"
          github_token: ${{ secrets.PAT }}
